### ISSUE TITLE
About'Enable awakeFromNib '

### ISSUE THREAD

**Issue by louyizhidu** [sabymike/MSSimpleGauge#13]
Could not find such a content，how to use 'Enable awakeFromNib', 
when i use: 
pod 'MSSimpleGauge',:git=>'https://github.com/sabymike/MSSimpleGauge.git', :branch=>'circlegauge' 
content is the same, i'm wrong?
 Hope support IB_DESIGNABLE

**Comment by sabymike** [comment]
Sorry, I don't know what you mean by "enabling awakeFromNib". SimpleGauge will call `[self setup];` in side its `awakeFromNib` method if thats what you mean. 

I have not added support for IB_DESIGNABLE but would happily accept a pull request if you'd like to provide it.
